server:
  port: 8008

spring:
  application:
     name: APIGATEWAY-SERVICE
  cloud:
    gateway:
      routes:
      - id: 
        uri: http://localhost:8081/
        predicates:
        - Path=/customer/**
      - id: 
        uri: http://localhost:8082/
        predicates:
        - Path=/washer/**
      - id: 
        uri: http://localhost:8083/
        predicates:
        - Path=/admin/**
      - id: 
        uri: http://localhost:8084/
        predicates:
        - Path=/order/**
      - id: 
        uri: http://localhost:8085/
        predicates:
        - Path=/payment/**
      
      